# Common Features
USER_ID_FIELD: userID
ITEM_ID_FIELD: itemID
#RATING_FIELD: rating
TIME_FIELD: timestamp

filter_out_cod_start_users: True
#交互
inter_file_name: 'baby.inter'

#评估
valid_metric: 'recall@20'
#metrics=['Recall', 'NDCG', 'Precision', 'MAP']
# name of features
vision_feature_file: 'image_feat.npy'
text_feature_file: 'text_feat.npy'
user_graph_dict_file: 'user_graph_dict.npy'

field_separator: "\t"
